
version: '3'
services:
  user-service-database:
    image: mariadb:10.4
    ports:
      - 3305:3306
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --event-scheduler=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service
    volumes:
      - ./database/user-service:/var/lib/mysql