--liquibase formatted mysql
--changeset tuandh:1.1
CREATE TABLE IF NOT EXISTS `user`  (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(15)  NOT NULL UNIQUE,
  `PASSWORD` varchar(200)  NULL DEFAULT NULL,
  `STATUS` tinyint(3) NULL DEFAULT 1,
  `UUID_DEVICE` varchar(40)  NULL DEFAULT NULL,
  `BIRTHDAY` varchar(50)  NULL DEFAULT NULL,
  `FULL_NAME` varchar(200)  NULL DEFAULT NULL,
  `EMAIL` varchar(100)  NULL DEFAULT NULL,
  `PHONE_NUMBER` varchar(15)  NULL DEFAULT NULL,
  `CREATED_DATE` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `UPDATED_DATE` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`ID`) USING BTREE
);